/**
 * Node-RED Plugin - Prompt contribution
 *
 * LLM context for Node-RED managed process.
 * Follows BashPlugin prompt pattern (array of strings joined with \n).
 */

export const NODERED_PROMPT = [
  '## nodered -- Managed Node-RED Process',
  'Node-RED runs as a managed child process of slashbot.',
  '',
  '**Available commands:**',
  '- `/nodered start` — Start Node-RED',
  '- `/nodered stop` — Stop Node-RED',
  '- `/nodered restart` — Restart Node-RED',
  '- `/nodered status` — Check health and view recent logs',
  '- `/nodered config` — View or update configuration',
  '- Alias: `/nr` works for all subcommands',
  '',
  '**Important:**',
  '- DO NOT use `bash` to start, stop, or manage Node-RED — use `/nodered` commands instead',
  '- DO NOT modify Node-RED `settings.js` directly — it is auto-generated on each start',
  '- Use `/nodered status` to check health and view recent logs',
  '- Node-RED Editor is accessible at `http://localhost:{port}/` (default port: 1880)',
  '',
  '## Flow Management Actions',
  'Use these action tags to manage Node-RED flows programmatically:',
  '',
  '**Create a flow** — deploy a new flow with nodes:',
  '```',
  '<nodered-flow-create>{"label":"My Flow","nodes":[{"id":"n1","type":"inject","wires":[["n2"]]},{"id":"n2","type":"debug"}]}</nodered-flow-create>',
  '```',
  '',
  '**List all flows:**',
  '```',
  '<nodered-flow-list />',
  '```',
  '',
  '**Delete a flow by ID:**',
  '```',
  '<nodered-flow-delete id="FLOW_ID" />',
  '```',
  '',
  '**Update an existing flow:**',
  '```',
  '<nodered-flow-update id="FLOW_ID">{"label":"Updated Label","nodes":[...]}</nodered-flow-update>',
  '```',
  '',
  '**Guidelines:**',
  '- Check Node-RED is running (`/nodered status`) before using flow actions',
  '- Use `<nodered-flow-list />` to discover flow IDs before delete/update',
  '- Flow JSON must include at least a `label` and `nodes` array for create',
  '- Use `/nodered flow list`, `/nodered flow info <id>`, `/nodered flow delete <id>` for direct commands',
].join('\n');
