/**
 * Project Configuration for MCP Server
 *
 * This file is generated by /specforge.mcp and customized for your project.
 * Modify the services, commands, and settings to match your stack.
 */

import { fileURLToPath } from "node:url";
import * as path from "node:path";

// Compute project root relative to this file's location
// From .mcp/project-server/{src,dist}/config.{ts,js} → project root is 3 levels up
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, "../../..");

export interface ServiceConfig {
  name: string;
  command: string;
  cwd?: string;
  env?: Record<string, string>;
  healthCheck?: {
    url: string;
    expectedStatus?: number;
    timeout?: number;
  };
  dependsOn?: string[];
  logFile?: string;
}

export interface ProjectConfig {
  name: string;
  rootDir: string;
  services: ServiceConfig[];
  docker?: {
    composeFile?: string;
    services?: string[];
  };
  browser?: {
    baseUrl: string;
    headless?: boolean;
  };
  api?: {
    baseUrl: string;
    defaultHeaders?: Record<string, string>;
  };
}

export const config: ProjectConfig = {
  name: "slashbot",
  rootDir: PROJECT_ROOT,

  services: [
    {
      name: "dev",
      command: "bun run src/index.ts",
      env: { "NODE_ENV": "development" },
    },
    {
      name: "gateway",
      command: "bun run src/index.ts gateway start",
      env: { "NODE_ENV": "development" },
      healthCheck: {
        url: "http://127.0.0.1:3001/health",
        timeout: 5000,
      },
    },
  ],

  browser: {
    baseUrl: "http://localhost:3000",
    headless: true
  },

  api: {
    baseUrl: "https://api.x.ai/v1",
    defaultHeaders: {
      "Content-Type": "application/json"
    }
  }
};
